name: Build and test

on:
  push:
  pull_request:
  schedule:
    # run daily, for initializing the cache if not generated yet.
    - cron: '41 3 * * *'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler: ["4.14.1"]
        experimental: [false]
          # include:
          # - ocaml-compiler: "5.2.0"
          #   experimental: true

    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Update apt cache
        run: sudo apt-get update

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use ocaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-repositories: |
            xs-opam: "."
          opam-pin: false
          dune-cache: true

      - name: Check whether there are packages with more than a version
        run: tools/no-duplicates-check.bash

      - name: Check whether there are unused packages
        run: tools/find-unused-packages.sh

      - name: Check whether there are unlicensed packages
        run: tools/license-check.sh

      - name: Build xs-toolstack, test its dependencies
        # opam install may ignore installing depexts sometimes
        # OPAMCOLOR is set to "always" by default and it breaks piping
        run: |
          OPAMERRLOGLEN=10000 OPAMCOLOR=NEVER opam list -s --required-by xs-toolstack | xargs opam depext -tu
          OPAMERRLOGLEN=10000 OPAMCOLOR=NEVER opam list -s --required-by xs-toolstack | xargs opam install -t

      - name: Uninstall unversioned packages
        # This should purge them from the cache, unversioned package have
        # 'master' as its version
        run: opam list | awk -F " " '$2 == "master" { print $1 }' |  xargs opam uninstall

      - name: Install developer tools
        run: opam install upstream-extra-dummy
